### ISSUE TITLE
conda don't find lsfm

### ISSUE THREAD

**Issue by marckatzenmaier** [menpo/lsfm#4]
Hi,
I have an problem during installing with conda
if I do the given command

conda create -n lsfm -c menpo python=3.5 lsfm 

the error occure:

PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
  - lsfm
You can search for packages on anaconda.org with
    anaconda search -t conda lsfm

but if I search it with:

anaconda search -t conda lsfm
it is shown:
Using Anaconda API: https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
     menpo/lsfm                |          | conda           | linux-64, win-32, win-64, osx-64
Found 1 packages

I hope you can help me with that error.
Thanks.

**Comment by adhereyuyu** [comment]
Hi，
I installing it on the Windows.I have the same problems with you.
I prepared the menpo firstly,Then download the source package of lsfm and open the folder, do the command
python setup.py install
So done







At 2017-02-28 00:00:58, "Cram13" <notifications@github.com> wrote:


Hi,
I have an problem during installing with conda
if I do the given command

conda create -n lsfm -c menpo python=3.5 lsfm

the error occure:

PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels:

lsfm
You can search for packages on anaconda.org with
anaconda search -t conda lsfm

but if I search it with:

anaconda search -t conda lsfm
it is shown:
Using Anaconda API: https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
Name | Version | Package Types | Platforms
------------------------- | ------ | --------------- | ---------------
menpo/lsfm | | conda | linux-64, win-32, win-64, osx-64
Found 1 packages

I hope you can help me with that error.
Thanks.

**Comment by jabooth** [comment]
@Cram13 @adhereyuyu so sorry, the conda packages for lsfm were not uploaded to the correct channels. I'll rectify this in the next day or two and let you know on here when it's ready.

**Comment by jabooth** [comment]
@Cram13 @adhereyuyu the issue should now be resolved, and I've confirmed it has been on linux. Will close once I've seen confirmation that the issue is resolved for win/mac too.
