### ISSUE TITLE
Question about the template

### ISSUE THREAD

**Issue by YunjieYu** [menpo/lsfm#41]
Hello, 

I have a question for the facial template. I am following the tutorial to generate the facial template from the BFM--running `lsfm init /path_to_directory/01_MorphableModel.mat`. However, I feel something wrong with the template, for example, the topology of the eye seems to be wrong.  Please see the picture below.

Can someone answer this question?

Thanks in advance!

![image](https://user-images.githubusercontent.com/44226851/97847069-f8cd4980-1d29-11eb-8c8e-0bb3f38737c8.png)

**Comment by YunjieYu** [comment]
And I also visualized the face mesh of BFM and noted that the number of vertices and faces for BFM is slightly larger than those for LSFM, please see the picture below. The BFM result seem to be normal. 

![image](https://user-images.githubusercontent.com/44226851/97852608-eb1bc200-1d31-11eb-8f51-c358e53a9252.png)

**Comment by jiaxiangshang** [comment]
> Hello,
> 
> I have a question for the facial template. I am following the tutorial to generate the facial template from the BFM--running `lsfm init /path_to_directory/01_MorphableModel.mat`. However, I feel something wrong with the template, for example, the topology of the eye seems to be wrong. Please see the picture below.
> 
> Can someone answer this question?
> 
> Thanks in advance!
> 
> ![image](https://user-images.githubusercontent.com/44226851/97847069-f8cd4980-1d29-11eb-8c8e-0bb3f38737c8.png)

Hi, man

Where have you find the tutorial? Can you share it, really thanks!

**Comment by YunjieYu** [comment]
> > Hello,
> > I have a question for the facial template. I am following the tutorial to generate the facial template from the BFM--running `lsfm init /path_to_directory/01_MorphableModel.mat`. However, I feel something wrong with the template, for example, the topology of the eye seems to be wrong. Please see the picture below.
> > Can someone answer this question?
> > Thanks in advance!
> > ![image](https://user-images.githubusercontent.com/44226851/97847069-f8cd4980-1d29-11eb-8c8e-0bb3f38737c8.png)
> 
> Hi, man
> 
> Where have you find the tutorial? Can you share it, really thanks!

Here https://github.com/menpo/lsfm/blob/master/CODE.md

**Comment by YunjieYu** [comment]
> Hi, man
> 
> Where have you find the tutorial? Can you share it, really thanks!

Here https://github.com/menpo/lsfm/blob/master/CODE.md

**Comment by jiaxiangshang** [comment]
Oh, really thanks for your help!
