### ISSUE TITLE
Package Missing and LSFM not found

### ISSUE THREAD

**Issue by SyedGilani** [menpo/lsfm#5]
Hi,
I have successfully installed the menpo as instructed. However when I run the command _C:\>conda create -n lsfm -c menpo python=3.5 lsfm_, it says:

Fetching package metadata .............
PackageNotFoundError: Package not found: '' Package missing in current win-64 ch
annels:
  - lsfm

---------------------
However, when I run the command _conda create -n lsfm python=3.5 -c menpo/lsfm_ The following happens:-

Fetching package metadata ....
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/menpo/lsfm

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
.........
Solving package specifications: .

Package plan for installation in environment E:\Codes\External_Libs\LSFM\Minicon
da2\envs\lsfm:

The following NEW packages will be INSTALLED:

    pip:            9.0.1-py35_1
    python:         3.5.3-0
    setuptools:     27.2.0-py35_1
    vs2015_runtime: 14.0.25123-0
    wheel:          0.29.0-py35_0

Proceed ([y]/n)? y

 To activate this environment, use:
 > activate lsfm

 To deactivate this environment, use:
 > deactivate lsfm

 for power-users using bash, you must source

---------------------------------
**After activation it is unable to recognize lsfm as a command**
(lsfm) C:\>lsfm --help
'lsfm' is not recognized as an internal or external command,
operable program or batch file.

I will greatly appreciate some help on this. 
Regards
Syed

**Comment by jabooth** [comment]
Hi @SyedGilani,

Really sorry for this problem, we've been caught up a little with issues on our build system, working through this issue now, should have it rectified today

**Comment by jabooth** [comment]
OK, the Linux build I have just verified is live, haven't got a win machine nearby to test but the issue should be resolved there also

**Comment by SyedGilani** [comment]
Hi James

Thank you for fixing it. Which Menpo Version do you recommend? The 2.7 or
3.5?

Regards

Syed

**Comment by jabooth** [comment]
@SyedGilani lsfm actually requires 3.5.

I would recommend you run the original install command with a new environment name to get everything cleanly setup now, e.g.:

```
> conda create -n lsfmv1 -c menpo python=3.5 lsfm
```
Then to use this new env,
```
> source activate lsfmv1
```
And you should be good to go.

**Comment by jabooth** [comment]
Closing as I believe this is now fully addressed.
