### ISSUE TITLE
How do I get the `01_MorphableModel.mat`?

### ISSUE THREAD

**Issue by ChuckGithub** [menpo/lsfm#6]
Hi,
When i run this command ‘lsfm -i ./input_data/ -o ./output_data/’，it prints
The LSFM template needs to be initialized from the Basel Face Model.
Please run:

 > lsfm init ./path/to/01_MorphableModel.mat
I don't know how to get this file,can you help me?
thank you.

**Comment by ChuckGithub** [comment]
already solved

**Comment by elliotresearcher** [comment]
hi can you please tell me where you got this file "01_MorphableModel.mat"
thanks in advance

**Comment by danindiana** [comment]
@elliotresearcher You will have to download the models from this site: https://faces.dmi.unibas.ch/bfm/main.php?nav=1-2&id=downloads

Hope this helps. I had that question too. Would have saved time if @ChuckGithub would have closed out the issue by providing the solution.

**Comment by flydragon2018** [comment]
no that link in the replied email
1
