### ISSUE TITLE
About "INITIAL PCA + PRUNE" error

### ISSUE THREAD

**Issue by ChuckGithub** [menpo/lsfm#7]
Hi,
when i run this command 'lsfm -i input_data -o output_data', I met some problems:

Input directory provided - scanning for importable meshes
Found 5 input meshes under: input_data
Resuming processing for output directory: D:\lsfm\lsfm\output_data
Current meshes are the same as the meshes in the input dir - resuming
Outputting results to D:\lsfm\lsfm\output_data

****** 1. DENSE CORRESPONDENCE **********

Correspondence: [==========] 100% (5/5) - done.

****** 1. INITIAL PCA + PRUNE **********
Traceback (most recent call last):
  File "E:\Program Files (x86)\Anaconda2\envs\lsfm\Scripts\lsfm-script.py", line 284, in <module>
    main(docopt(__doc__))
  File "E:\Program Files (x86)\Anaconda2\envs\lsfm\Scripts\lsfm-script.py", line 280, in main
    pca_and_prune(r, verbose=verbose)
  File "E:\Program Files (x86)\Anaconda2\envs\lsfm\Scripts\lsfm-script.py", line 99, in pca_and_prune
    verbose=True)
  File "E:\Program Files (x86)\Anaconda2\envs\lsfm\lib\site-packages\lsfm\model.py", line 14, in pca_and_weights
    model = PCAModel(meshes, verbose=verbose)
  File "E:\Program Files (x86)\Anaconda2\envs\lsfm\lib\site-packages\menpo\model\pca.py", line 1199, in __init__
    return_template=True, verbose=verbose)
  File "E:\Program Files (x86)\Anaconda2\envs\lsfm\lib\site-packages\menpo\math\linalg.py", line 125, in as_matrix
    template = vectorizables[0]
  File "E:\Program Files (x86)\Anaconda2\envs\lsfm\lib\site-packages\menpo\base.py", line 482, in __getitem__
    return self._callables[slice_]()
IndexError: list index out of range

And another problem 
E:\Program Files (x86)\Anaconda2\envs\lsfm\lib\site-packages\menpo\image\base.py:2652: MenpoDeprecationWarning: This method is no longer supported and will be removed in a future version of Menpo. Use .pixels_with_channels_at_back instead.
  MenpoDeprecationWarning)
0 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [=         ] 12% (1/8) - 00:00:16 remaining                     1 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [==        ] 25% (2/8) - 00:00:12 remaining                     2 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [===       ] 37% (3/8) - 00:00:10 remaining                     3 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [=====     ] 50% (4/8) - 00:00:08 remaining                     4 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [======    ] 62% (5/8) - 00:00:06 remaining                     5 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [=======   ] 75% (6/8) - 00:00:04 remaining                     6 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [========  ] 87% (7/8) - 00:00:02 remaining                     7 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [==========] 100% (8/8) - done.

**Comment by ChuckGithub** [comment]
E:\Program Files (x86)\Anaconda2\envs\lsfm\lib\site-packages\menpo\image\base.py:2652: MenpoDeprecationWarning: This method is no longer supported and will be removed in a future version of Menpo. Use .pixels_with_channels_at_back instead.
  MenpoDeprecationWarning)
0 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [=         ] 12% (1/8) - 00:00:16 remaining                     1 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [==        ] 25% (2/8) - 00:00:12 remaining                     2 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [===       ] 37% (3/8) - 00:00:10 remaining                     3 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [=====     ] 50% (4/8) - 00:00:08 remaining                     4 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [======    ] 62% (5/8) - 00:00:06 remaining                     5 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [=======   ] 75% (6/8) - 00:00:04 remaining                     6 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [========  ] 87% (7/8) - 00:00:02 remaining                     7 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [==========] 100% (8/8) - done.

**Comment by jerry-xidian** [comment]
how you slove the first question?
thanks

**Comment by jerry-xidian** [comment]
if you notice this ,help me?
