### ISSUE TITLE
About cropped model

### ISSUE THREAD

**Issue by ChuckGithub** [menpo/lsfm#9]
Hi,
Can you help me?I want to know what is the role of this code.it is in the 'lsfm/lsfm/io.py' line 144
`# if name.endswith('_tri'):
    #     masking_info = mio.import_pickle(
    #         model_path.parent.parent / 'radial_mask_tri.pkl')
    #     mdict['map_crop_to_full'] = masking_info['map_cropped_to_full']
    #     mdict['map_full_to_cropped'] = masking_info['map_full_to_cropped']
    #     name = name.split('_tri')[0]`
and i want to get the cropped model what should i do?

**Comment by jabooth** [comment]
Hi @ChuckGithub,

I'm not sure what you mean here. To be clear, this repo is only the source code for LSFM - to access the actual model you would need to go here and apply for access: http://ibug.doc.ic.ac.uk/resources/lsfm

The model files you can download if approved include the masking info referenced in the documentation. Hope that clears it up?
